### PR TITLE
Migrate to Async API

### PR DESCRIPTION
**Pull request by wishawa**
Replace the existing blocking API with async tokio and reqwest.

### CODE REVIEW

**Comment by KongouDesu** [comment]
Hi @wishawa 

Looks good. I've changed it to use a file instead of /dev/urandom to make sure the test will still pass on Windows.
I've also bumped the crate version in order for it to be published.

Let me know if you have any comments, otherwise I'll merge and publish it.

**Comment by wishawa** [comment]
I tried to make the API for creating Body for file upload a little more symmetric in 935d71f55eb72c9aa02d754c8a7bd21c6c94892d, but later decided that it is probably not worth having to specify dependency version for `bytes`, so I reverted it in 7540d0854f0607220e75ff2ebddcc0a094ef1c14.

Between that, I split the utils part of the crate into separate features that is enabled by default.

**Comment by wishawa** [comment]
> Looks good. I've changed it to use a file instead of /dev/urandom to make sure the test will still pass on Windows.

Sorry about that. I completely forgot!

> Let me know if you have any comments, otherwise I'll merge and publish it.

Let's get it published!

**Comment by KongouDesu** [comment]
Seems good.

I'm hoping I'll get around to doing an async rewrite from the ground up soon(-ish). There's some new B2 endpoints I'd like to get working, not to mention the calls that this _already_ isn't implementing.
But for now this should get the job done.

There's some changes in the blocking API that aren't published either. I'll publish that as 0.3.2 and publish the async as 0.4.0

**Pull request merged**
